import { NextResponse } from 'next/server';

const frases = [
    "Hoje minha preguiça está em modo maratona.",
    "A academia que lute, hoje tô no sofá.",
    "Preciso proteger o mundo... começando por não suar.",
    "Minhas roupas de ginástica tiraram férias.",
    "Meu corpo pediu descanso, e eu obedeço.",
    "O único levantamento que farei hoje é do controle remoto.",
    "Vou fazer exercício… de digitar no celular.",
    "Hoje treino só o meu talento pra enrolar.",
    "O único peso que levantei foi o moral dos amigos.",
    "Minha motivação está mais pesada que eu.",
    "Hoje não, meu músculo está em greve.",
    "O sofá fez uma oferta que não pude recusar.",
    "Treino mental: pensando em ir pra academia.",
    "Vou fazer uma série de esticar na cama.",
    "O treino do dia: evitar o treino do dia.",
    "Meu relógio marcava hora de descanso, não de exercício.",
    "Hoje meu esporte é a maratona de séries.",
    "Meu corpo pediu pausa para manutenção.",
    "Malhar dói, e eu prefiro o prazer.",
    "Minha esteira está com ciúmes do sofá.",
    "Vou fortalecer meu direito de folga hoje.",
    "Levantar peso? Só se for o da culpa.",
    "A academia pode esperar, eu também.",
    "Hoje treino para o campeonato de não fazer nada.",
    "Minha prioridade é evitar lesão de esforço.",
    "Meus músculos estão de férias coletivas.",
    "No ranking de prioridades, academia está em último.",
    "O melhor treino é o que não acontece.",
    "Vou suar frio de medo de ir pra academia.",
    "Hoje o que pesa é a consciência.",
    "O único supino que faço hoje é o na cama.",
    "Minha dieta de desculpas está ótima.",
    "A preguiça é o melhor personal trainer hoje.",
    "O melhor alongamento é me esticar no sofá.",
    "Hoje treino o poder da procrastinação.",
    "Meu corpo está em modo avião.",
    "Minha academia é o quarto, e meu exercício é dormir.",
    "Hoje tô na modalidade 'descanso olímpico'.",
    "O melhor exercício hoje é rir das minhas desculpas.",
    "Vou deixar os pesos descansando comigo.",
    "Hoje a balança está de folga comigo também.",
    "Hoje só corro o risco de não ir à academia.",
    "Meu treino é fazer nada com excelência.",
    "Meu treinador imaginário está de folga.",
    "Vou exercitar a arte do sofá hoje.",
    "Meu relógio biológico marca 'soneca'.",
    "Hoje eu ganho medalha de ouro em preguiça.",
    "Vou fortalecer minha desculpa favorita.",
    "Meu corpo pediu um descanso estratégico.",
    "Treino? Hoje só no videogame.",
    "Meus músculos preferem Netflix ao supino.",
    "Minha motivação está em modo avião.",
    "A academia está no meu futuro distante.",
    "Hoje treino o músculo do 'depois eu faço'.",
    "Vou treinar o poder do convencimento pra não ir.",
    "Hoje o descanso é meu exercício favorito.",
    "Vou malhar só a imaginação.",
    "Hoje tô fazendo jejum de suor.",
    "A única corrida que faço hoje é na memória.",
    "Hoje o único exercício é respirar fundo para não ir.",
    "Minha rotina fitness inclui muitas pausas.",
    "Hoje meu corpo está indisponível para malhar.",
    "Meu plano de treino inclui muita preguiça.",
    "Hoje vou levantar a taça da folga.",
    "Vou praticar o esporte do sofá sentado.",
    "Minha academia particular é o meu quarto.",
    "Hoje a motivação está de férias.",
    "Minha desculpa está super condicionada.",
    "Hoje meu treino é dominar a arte da soneca.",
    "Vou deixar os pesos descansando comigo.",
    "Hoje treino para ser campeão em não fazer nada.",
    "Meu corpo pediu licença para o descanso.",
    "Hoje vou evitar o esforço físico com talento.",
    "Meu exercício é pensar em exercícios.",
    "Hoje minha meta é não suar nem um pouco.",
    "Minha rotina fitness foi substituída por descanso.",
    "Vou exercitar o dom da preguiça.",
    "Hoje treino a arte de não ir à academia.",
    "Meu corpo está no modo hibernação.",
    "Hoje vou praticar o esporte da procrastinação.",
    "Meu descanso é parte do treino, certo?",
    "Hoje vou dar um descanso merecido pra mim.",
    "Minha prioridade é o conforto do sofá.",
    "Hoje a academia está suspensa no calendário.",
    "Vou descansar os músculos e a alma.",
    "Hoje só faço exercício de levantar da cama.",
    "Minha força está toda concentrada no controle remoto.",
    "Hoje treino o dom da desculpa perfeita.",
    "Vou malhar só os dedos no celular.",
    "Hoje o treino é para relaxar de verdade.",
    "Meu compromisso é com a minha preguiça.",
    "Hoje só corro o risco de ficar no sofá.",
    "Vou deixar a academia para amanhã, ou depois.",
    "Hoje treino para ser mestre do descanso.",
    "Minha vontade de malhar está em modo avião.",
    "Hoje o único peso que levanto é o moral do time.",
    "Minha academia hoje é o tapete da sala.",
    "Hoje o suor é só o da mente pensando no treino.",
    "Vou fazer exercício… de não fazer exercícios.",
    "Hoje vou malhar só o bom humor.",
    "Minha meta hoje é não fazer nada e fazer bem.",
    "Hoje o treino é para a mente, corpo fica no descanso.",
    "Meu plano de treino é não ter plano nenhum."
];

export async function GET() {
    return NextResponse.json({ frases });
}