import { NextResponse } from 'next/server';

const frases = [
    "Hoje minha preguiça está em modo maratona.",
    "A academia que lute, hoje tô no sofá.",
    "Preciso proteger o mundo... começando por não suar.",
    "Minhas roupas de ginástica tiraram férias.",
    "Meu corpo pediu descanso, e eu obedeço.",
    "O único levantamento que farei hoje é do controle remoto.",
    "Vou fazer exercício… de digitar no celular.",
    "Hoje treino só o meu talento pra enrolar.",
    "O único peso que levantei foi o moral dos amigos.",
    "Minha motivação está mais pesada que eu.",
    "Hoje não, meu músculo está em greve.",
    "O sofá fez uma oferta que não pude recusar.",
    "Treino mental: pensando em ir pra academia.",
    "Vou fazer uma série de esticar na cama.",
    "O treino do dia: evitar o treino do dia.",
    "Meu relógio marcava hora de descanso, não de exercício.",
    "Hoje meu esporte é a maratona de séries.",
    "Meu corpo pediu pausa para manutenção.",
    "Malhar dói, e eu prefiro o prazer.",
    "Minha esteira está com ciúmes do sofá.",
    "Vou fortalecer meu direito de folga hoje.",
    "Levantar peso? Só se for o da culpa.",
    "A academia pode esperar, eu também.",
    "Hoje treino para o campeonato de não fazer nada.",
    "Minha prioridade é evitar lesão de esforço.",
    "Meus músculos estão de férias coletivas.",
    "No ranking de prioridades, academia está em último.",
    "O melhor treino é o que não acontece.",
    "Vou suar frio de medo de ir pra academia.",
    "Hoje o que pesa é a consciência.",
    "O único supino que faço hoje é o na cama.",
    "Minha dieta de desculpas está ótima.",
    "A preguiça é o melhor personal trainer hoje.",
    "O melhor alongamento é me esticar no sofá.",
    "Hoje treino o poder da procrastinação.",
    "Meu corpo está em modo avião.",
    "Minha academia é o quarto, e meu exercício é dormir.",
    "Hoje tô na modalidade 'descanso olímpico'.",
    "O melhor exercício hoje é rir das minhas desculpas.",
    "Vou deixar os pesos descansando comigo.",
    "Hoje a balança está de folga comigo também.",
    "Hoje só corro o risco de não ir à academia.",
    "Meu treino é fazer nada com excelência.",
    "Meu treinador imaginário está de folga.",
    "Vou exercitar a arte do sofá hoje.",
    "Meu relógio biológico marca 'soneca'.",
    "Hoje eu ganho medalha de ouro em preguiça.",
    "Vou fortalecer minha desculpa favorita.",
    "Meu corpo pediu um descanso estratégico.",
    "Treino? Hoje só no videogame.",
    "Meus músculos preferem Netflix ao supino.",
    "Minha motivação está em modo avião.",
    "A academia está no meu futuro distante.",
    "Hoje treino o músculo do 'depois eu faço'.",
    "Vou treinar o poder do convencimento pra não ir.",
    "Hoje o descanso é meu exercício favorito.",
    "Vou malhar só a imaginação.",
    "Hoje tô fazendo jejum de suor.",
    "A única corrida que faço hoje é na memória.",
    "Hoje o único exercício é respirar fundo para não ir.",
    "Minha rotina fitness inclui muitas pausas.",
    "Hoje meu corpo está indisponível para malhar.",
    "Meu plano de treino inclui muita preguiça.",
    "Hoje vou levantar a taça da folga.",
    "Vou praticar o esporte do sofá sentado.",
    "Minha academia particular é o meu quarto.",
    "Hoje a motivação está de férias.",
    "Minha desculpa está super condicionada.",
    "Hoje meu treino é dominar a arte da soneca.",
    "Vou deixar os pesos descansando comigo.",
    "Hoje treino para ser campeão em não fazer nada.",
    "Meu corpo pediu licença para o descanso.",
    "Hoje vou evitar o esforço físico com talento.",
    "Meu exercício é pensar em exercícios.",
    "Hoje minha meta é não suar nem um pouco.",
    "Minha rotina fitness foi substituída por descanso.",
    "Vou exercitar o dom da preguiça.",
    "Hoje treino a arte de não ir à academia.",
    "Meu corpo está no modo hibernação.",
    "Hoje vou praticar o esporte da procrastinação.",
    "Meu descanso é parte do treino, certo?",
    "Hoje vou dar um descanso merecido pra mim.",
    "Minha prioridade é o conforto do sofá.",
    "Hoje a academia está suspensa no calendário.",
    "Vou descansar os músculos e a alma.",
    "Hoje só faço exercício de levantar da cama.",
    "Minha força está toda concentrada no controle remoto.",
    "Hoje treino o dom da desculpa perfeita.",
    "Vou malhar só os dedos no celular.",
    "Hoje o treino é para relaxar de verdade.",
    "Meu compromisso é com a minha preguiça.",
    "Hoje só corro o risco de ficar no sofá.",
    "Vou deixar a academia para amanhã, ou depois.",
    "Hoje treino para ser mestre do descanso.",
    "Minha vontade de malhar está em modo avião.",
    "Hoje o único peso que levanto é o moral do time.",
    "Minha academia hoje é o tapete da sala.",
    "Hoje o suor é só o da mente pensando no treino.",
    "Vou fazer exercício… de não fazer exercícios.",
    "Hoje vou malhar só o bom humor.",
    "Minha meta hoje é não fazer nada e fazer bem.",
    "Hoje o treino é para a mente, corpo fica no descanso.",
    "Meu plano de treino é não ter plano nenhum.",
    "meu gato deitou no meu colo e não tive coragem de levantar",
    "minha calça de treino desapareceu misteriosamente",
    "acho que sonhei que fui e acordei cansado",
    "os astros não estão alinhados para agachar hoje",
    "hoje é feriado no meu país imaginário",
    "minha geladeira precisava de companhia",
    "minha pantufa não deixou eu sair de casa",
    "a gravidade estava mais forte hoje",
    "meu horóscopo mandou descansar",
    "minha alma está malhando no plano astral",
    "minha cama venceu o duelo novamente",
    "a preguiça me pegou em um mata-leão",
    "meu tênis fugiu de mim",
    "não encontrei meu fone, sem música não dá",
    "esqueci como faz agachamento",
    "estava treinando o olhar 43 no espelho",
    "meu reflexo disse: 'fica mais um pouco'",
    "descobri que levantar controle remoto também é um exercício",
    "minha planta precisava de atenção hoje",
    "o sofá me fez uma proposta irrecusável",
    "o universo me mandou um sinal: maratona de séries",
    "estou fazendo jejum de exercícios",
    "vou malhar amanhã. Prometo. De novo.",
    "minha barriga tá na frente, não consigo ver a motivação",
    "meu corpo entrou em modo avião",
    "minha sombra foi e voltou sozinha",
    "Hoje é dia internacional do sofá, não posso desrespeitar.",
    "A academia me disse que precisa de um tempo.",
    "Meu tênis pediu férias remuneradas.",
    "Fui levantar o cobertor e já foi meu treino do dia.",
    "Se correr fosse saudável, o carteiro era imortal.",
    "Musculação? Só se for nos dedos jogando videogame.",
    "Hoje a única barra que vou encarar é de chocolate.",
    "Fui pra academia... no Google Maps.",
    "Treinar? Estou treinando a paciência hoje.",
    "Não posso ir, minha pantufa não deixou.",
    "Academia? Prefiro lidar com pesos emocionais.",
    "A única repetição que faço hoje é repetir o prato.",
    "Acordei fitness: fit no sofá.",
    "Vou malhar... malhar o juízo dos outros com memes.",
    "O treino de hoje é carregar o celular pra todo canto.",
    "Minha balança me bloqueou, tô de luto.",
    "Já suei só de pensar em ir pra academia.",
    "Hoje estou no modo repouso prolongado.",
    "Só corro riscos. Exercício físico, não.",
    "Hoje é leg day... de legendar stories de comida.",
    "Estou me poupando pra maratona de séries.",
    "O único levantamento que farei é da moral do grupo.",
    "Minha motivação foi malhar e nunca mais voltou.",
    "Paguei a academia pra dizer que invisto em saúde.",
    "Acordei com espírito fitness, mas ele dormiu de novo.",
    "Fui à academia ontem... em pensamento.",
    "Se fosse fácil, até eu faria. Como não é, passo.",
    "O personal me expulsou por excesso de conversa fiada.",
    "Meu treino de hoje é resistir à vontade de treinar.",
    "Acordei com a meta de não suar. Meta atingida!",
    "A esteira me olhou torto. Fiquei com medo.",
    "Meu corpo pediu socorro só de ouvir 'academia'.",
    "Já estou em forma: redonda é uma forma.",
    "Dizem que rir emagrece. Vou maratonar comédias.",
    "Malhar atrapalha meu sono da beleza.",
    "Meu abdômen está definido: bem escondido.",
    "Desenvolvi alergia a pesos e suor.",
    "Hoje é dia de descanso do descanso.",
    "Vou só fazer um alongamento... de ideias.",
    "Não estou evitando academia, estou economizando energia.",
    "Minha roupa de treino desapareceu misteriosamente.",
    "Se tivesse wi-fi na esteira, talvez eu pensasse.",
    "Hoje minha prioridade é a saúde mental. E pizza.",
    "Minha vibe hoje é yoga mental: não mover um músculo.",
    "Eu treino... minha capacidade de dizer não ao treino.",
    "A academia me persegue. Sonhei com ela me cobrando.",
    "Vou esperar a moda da academia passar.",
    "Se levantar da cama conta como agachamento, já treinei.",
    "Hoje estou focado: focado em não me mexer.",
    "Acordei com 1% de bateria corporal. Sem carregador.",
    "Hoje o treino é de resistência: resistir à academia.",
    "Meu treinador espiritual me proibiu de malhar.",
    "Se fosse pra sofrer, eu assistia novela triste.",
    "Meu músculo mais trabalhado é o da desculpa.",
    "Caminhar até a geladeira já é meu cardio.",
    "Malhar? Só se for o juízo dos outros no grupo de zap.",
    "Não fui pra academia porque estava estudando desculpas.",
    "Meu corpo gritou ‘socorro’ só de ouvir ‘treino’!",
    "Tô em dia com a academia... dia sim, 10 não.",
    "Hoje minha academia é emocional.",
    "Eu até ia, mas tropecei na procrastinação.",
    "A única carga que aguento hoje é emocional.",
    "Malhar? Só se for pipoca no micro-ondas.",
    "Corpo são, mente cansada, descanso autorizado.",
    "Meu relógio biológico tá no modo soneca.",
    "Não vou, tô esperando o apocalipse fitness passar.",
    "Prefiro agachar para pegar a comida caída no chão.",
    "Acordei tão motivado quanto uma pedra.",
    "Se academia fosse série, talvez eu assistisse.",
    "Meu look de treino virou pijama. Aceita que dói menos.",
    "Hoje treino de peso: levantar o garfo até a boca.",
    "Vou praticar o esporte olímpico de dormir até tarde.",
    "Academia causa suor. Suor causa banho. Fica difícil.",
    "Estou praticando o esporte de alto rendimento: enrolação.",
    "Minha única série hoje será a da Netflix.",
    "Comi tanto que já fiz meu treino de mandíbula.",
    "Hoje é dia de regeneração... de todas as preguiças.",
    "Minha vibe hoje é 'só observo'.",
    "O sofá me contratou como estagiário do conforto.",
    "Se fosse treino de memes, eu era campeão mundial.",
    "O personal tentou me ligar. Bloqueei.",
    "Malho sim: malho a arte de enrolar com perfeição.",
    "Hoje só treino se for pra abrir o pote de sorvete.",
    "Pisar na academia quebra meu feng shui.",
    "Treino de hoje é leve: levantar o ego.",
    "Já estou exercitando minha desculpa de amanhã.",
    "Fui ver os pesos e eles estavam muito pesados.",
    "Meu propósito hoje é não suar.",
    "Não é preguiça, é estratégia de descanso avançado.",
    "Minhas panturrilhas pediram demissão.",
    "Corpo mole é meu estilo de vida.",
    "Comi proteína... no recheio da coxinha.",
    "Me exercito todo dia... para fugir do esforço físico.",
    "Acordei e pensei: ‘vamos adiar mais esse sonho’",
    "Malho o cérebro com charadas e memes.",
    "Minha meta é chegar ao fim do dia sem suar.",
    "O único whey que tomo é de açaí com leite condensado.",
    "Estou num relacionamento sério com meu travesseiro.",
    "A academia é tóxica, só me faz sofrer.",
    "Treinei tanto em outra vida que tô de folga nessa.",
    "Hoje estou fazendo pilates mentais.",
    "Musculação não combina com meu signo.",
    "O dia tá tão bonito pra eu ficar me cansando.",
    "Comi tanto que estou pesado emocionalmente.",
    "Vou malhar a mente... com fofoca.",
    "Minhas articulações se recusaram a cooperar.",
    "Amanhã eu vou. Mentira, mas amanhã é outro dia.",
    "Hoje estou praticando a arte da imobilidade.",
    "O treino que me atrai é de absorver memes.",
];

export async function GET() {
    return NextResponse.json({ frases });
}